### ISSUE TITLE
[FEATURE] static IP address

### ISSUE THREAD

**Issue by gzi01** [softwarecrash/Victron2MQTT#28]
### Is your feature request related to a problem? Please describe

I suggest a config interface to setup a static IP address. Currently it seems Victron2MQTT uses DHCP only.

### Describe the solution you'd like

configuration entry in the captive screen

### Describe alternatives you've considered

option in the http://xxx/settingsedit page

### Additional context

n/a

**Comment by softwarecrash** [comment]
its on the To-Do list
